"""Multi-agent contracts, registry, state merge, serialization, and planning."""

from multi_agent.contracts import (
    ActionProposal,
    ActionRiskLevel,
    AgentAuthority,
    AgentCapability,
    AgentError,
    AgentErrorCategory,
    AgentExecutionContext,
    AgentResult,
    AgentTask,
    ComplexityDecision,
    Evidence,
    EvidenceType,
    ExecutionBudget,
    ExecutionUsage,
    MultiAgentState,
    ProviderMetadata,
    StrictContract,
    TokenUsage,
    ToolAuthority,
    ToolCallRecord,
    ToolDescriptor,
    from_crm_writer_proposal,
    from_productivity_proposal,
)
from multi_agent.errors import (
    BudgetExceededError,
    CapabilityValidationError,
    DisabledAgentError,
    DuplicateAgentError,
    DuplicateToolError,
    ForeignTenantEvidenceError,
    MergeConflictError,
    MultiAgentError,
    ProposalHashMismatchError,
    SerializationError,
    UnauthorizedToolError,
    UnknownAgentError,
    UnknownToolError,
)
from multi_agent.integrity import compute_proposal_hash
from multi_agent.registry import (
    AgentHandler,
    AgentRegistry,
    RegistrySnapshot,
    ToolCatalog,
)
from multi_agent.serialization import (
    canonicalize,
    content_hash,
    deserialize_contract,
    serialize_contract,
    serialize_set_for_json,
    stable_hash,
    validate_strict_json,
)
from multi_agent.state import MergeConflict, MergedState, merge_parallel_results

# Phase 3 — planning
from multi_agent.complexity_gate import (
    DETERMINISTIC_EVENT_TYPES,
    KAFKA_TOPIC_TO_EVENT_TYPE,
    REASON_CONFLICTING_SIGNALS,
    REASON_CROSS_DOMAIN_OBJECTIVE,
    REASON_CUSTOMER_RECOVERY_TEMPLATE,
    REASON_FIXED_EVENT_ALLOWLIST,
    REASON_MULTIPLE_TASK_TYPES,
    REASON_SINGLE_DOMAIN_SINGLE_TASK,
    RuleBasedComplexityGate,
)
from multi_agent.planning import (
    CODE_APPROVAL_REQUEST_MISSING_PROPOSE,
    CODE_INTENT_CYCLE,
    CODE_INTENT_DUPLICATE_ID,
    CODE_INTENT_MISSING_DEPENDENCY,
    CODE_WRITE_REQUEST_MISSING_PROPOSE,
    MAX_ASSIGNMENT_COMBINATIONS,
    PLANNER_VERSION,
    PlanDraft,
    PlanValidationIssue,
    PlanValidationReport,
    PlannedTask,
    PlanningRequest,
    PlanningSignals,
    RequestedTask,
    TaskIntent,
    TOOL_TO_AGENT_AUTHORITY,
    build_expected_planned_tasks,
    canonical_request_payload,
    compute_plan_hash,
    compute_request_hash,
    effective_domains,
    effective_task_types,
    resolve_agent_assignment,
    resolve_candidate_agents,
    resolve_expected_intents,
    task_intent_from_requested_task,
    validate_intent_graph,
    validate_intent_tool_authority,
    validate_write_approval_requirements,
)
from multi_agent.planning_errors import (
    AmbiguousAgentSelectionError,
    BudgetExceededPlanningError,
    InsufficientContextError,
    PlanCycleError,
    PlanIntegrityError,
    PlanValidationError,
    PlanningError,
    PlanningInputError,
    RegistryVersionMismatchError,
    UnsupportedCapabilityError,
)
from multi_agent.planning_templates import (
    CUSTOMER_RECOVERY_DOMAIN,
    DEFAULT_CUSTOMER_RECOVERY_TEMPLATE,
    CustomerRecoveryTemplate,
    INTENT_CUSTOMER_CONTEXT,
    INTENT_KNOWLEDGE_RECOMMENDATION,
    INTENT_RECOVERY_METRICS,
    INTENT_SALES_RISK_ANALYSIS,
    INTENT_SUPPORT_ANALYSIS,
)
from multi_agent.plan_validator import PlanValidator
from multi_agent.planner import DeterministicPlanner

__all__ = [
    # Phase 2
    "ActionProposal",
    "ActionRiskLevel",
    "AgentAuthority",
    "AgentCapability",
    "AgentError",
    "AgentErrorCategory",
    "AgentExecutionContext",
    "AgentHandler",
    "AgentRegistry",
    "AgentResult",
    "AgentTask",
    "BudgetExceededError",
    "CapabilityValidationError",
    "ComplexityDecision",
    "DisabledAgentError",
    "DuplicateAgentError",
    "DuplicateToolError",
    "Evidence",
    "EvidenceType",
    "ExecutionBudget",
    "ExecutionUsage",
    "ForeignTenantEvidenceError",
    "MergeConflict",
    "MergeConflictError",
    "MergedState",
    "MultiAgentError",
    "MultiAgentState",
    "ProposalHashMismatchError",
    "ProviderMetadata",
    "RegistrySnapshot",
    "SerializationError",
    "StrictContract",
    "TokenUsage",
    "ToolAuthority",
    "ToolCallRecord",
    "ToolCatalog",
    "ToolDescriptor",
    "UnauthorizedToolError",
    "UnknownAgentError",
    "UnknownToolError",
    "canonicalize",
    "compute_proposal_hash",
    "content_hash",
    "deserialize_contract",
    "from_crm_writer_proposal",
    "from_productivity_proposal",
    "merge_parallel_results",
    "serialize_contract",
    "serialize_set_for_json",
    "stable_hash",
    "validate_strict_json",
    # Phase 3 — Complexity Gate
    "DETERMINISTIC_EVENT_TYPES",
    "KAFKA_TOPIC_TO_EVENT_TYPE",
    "REASON_CONFLICTING_SIGNALS",
    "REASON_CROSS_DOMAIN_OBJECTIVE",
    "REASON_CUSTOMER_RECOVERY_TEMPLATE",
    "REASON_FIXED_EVENT_ALLOWLIST",
    "REASON_MULTIPLE_TASK_TYPES",
    "REASON_SINGLE_DOMAIN_SINGLE_TASK",
    "RuleBasedComplexityGate",
    # Phase 3 — Planning
    "CODE_APPROVAL_REQUEST_MISSING_PROPOSE",
    "CODE_INTENT_CYCLE",
    "CODE_INTENT_DUPLICATE_ID",
    "CODE_INTENT_MISSING_DEPENDENCY",
    "CODE_WRITE_REQUEST_MISSING_PROPOSE",
    "MAX_ASSIGNMENT_COMBINATIONS",
    "PLANNER_VERSION",
    "PlanDraft",
    "PlanValidationIssue",
    "PlanValidationReport",
    "PlannedTask",
    "PlanningRequest",
    "PlanningSignals",
    "RequestedTask",
    "TaskIntent",
    "TOOL_TO_AGENT_AUTHORITY",
    "build_expected_planned_tasks",
    "canonical_complexity_payload",
    "canonical_request_payload",
    "compute_plan_hash",
    "compute_request_hash",
    "effective_domains",
    "effective_task_types",
    "resolve_agent_assignment",
    "resolve_candidate_agents",
    "resolve_expected_intents",
    "task_intent_from_requested_task",
    "validate_intent_graph",
    "validate_intent_tool_authority",
    "validate_write_approval_requirements",
    # Phase 3 — Errors
    "AmbiguousAgentSelectionError",
    "BudgetExceededPlanningError",
    "InsufficientContextError",
    "PlanCycleError",
    "PlanIntegrityError",
    "PlanValidationError",
    "PlanningError",
    "PlanningInputError",
    "RegistryVersionMismatchError",
    "UnsupportedCapabilityError",
    # Phase 3 — Templates
    "CUSTOMER_RECOVERY_DOMAIN",
    "DEFAULT_CUSTOMER_RECOVERY_TEMPLATE",
    "CustomerRecoveryTemplate",
    "INTENT_CUSTOMER_CONTEXT",
    "INTENT_KNOWLEDGE_RECOMMENDATION",
    "INTENT_RECOVERY_METRICS",
    "INTENT_SALES_RISK_ANALYSIS",
    "INTENT_SUPPORT_ANALYSIS",
    # Phase 3 — Validator & Planner
    "PlanValidator",
    "DeterministicPlanner",
]
