"""Multi-agent contracts, registry, state merge, and serialization."""

from multi_agent.contracts import (
    ActionProposal,
    ActionRiskLevel,
    AgentAuthority,
    AgentCapability,
    AgentError,
    AgentErrorCategory,
    AgentExecutionContext,
    AgentResult,
    AgentTask,
    ComplexityDecision,
    Evidence,
    EvidenceType,
    ExecutionBudget,
    MultiAgentState,
    ProviderMetadata,
    StrictContract,
    TokenUsage,
    ToolAuthority,
    ToolCallRecord,
    _compute_proposal_hash,
    from_crm_writer_proposal,
    from_productivity_proposal,
)
from multi_agent.errors import (
    BudgetExceededError,
    CapabilityValidationError,
    DisabledAgentError,
    DuplicateAgentError,
    ForeignTenantEvidenceError,
    MergeConflictError,
    MultiAgentError,
    ProposalHashMismatchError,
    SerializationError,
    UnauthorizedToolError,
    UnknownAgentError,
    UnknownToolError,
)
from multi_agent.registry import (
    AgentHandler,
    AgentRegistry,
    RegistrySnapshot,
    ToolCatalog,
    ToolDescriptor,
)
from multi_agent.serialization import (
    canonicalize,
    content_hash,
    deserialize_contract,
    serialize_contract,
    serialize_set_for_json,
    stable_hash,
)
from multi_agent.state import (
    MergeConflict,
    MergedState,
    merge_parallel_results,
)

__all__ = [
    # Contracts
    "ActionProposal",
    "ActionRiskLevel",
    "AgentAuthority",
    "AgentCapability",
    "AgentError",
    "AgentErrorCategory",
    "AgentExecutionContext",
    "AgentResult",
    "AgentTask",
    "ComplexityDecision",
    "Evidence",
    "EvidenceType",
    "ExecutionBudget",
    "MultiAgentState",
    "ProviderMetadata",
    "StrictContract",
    "TokenUsage",
    "ToolAuthority",
    "ToolCallRecord",
    "_compute_proposal_hash",
    "from_crm_writer_proposal",
    "from_productivity_proposal",
    # Errors
    "BudgetExceededError",
    "CapabilityValidationError",
    "DisabledAgentError",
    "DuplicateAgentError",
    "ForeignTenantEvidenceError",
    "MergeConflictError",
    "MultiAgentError",
    "ProposalHashMismatchError",
    "SerializationError",
    "UnauthorizedToolError",
    "UnknownAgentError",
    "UnknownToolError",
    # Registry
    "AgentHandler",
    "AgentRegistry",
    "RegistrySnapshot",
    "ToolCatalog",
    "ToolDescriptor",
    # Serialization
    "canonicalize",
    "content_hash",
    "deserialize_contract",
    "serialize_contract",
    "serialize_set_for_json",
    "stable_hash",
    # State
    "MergeConflict",
    "MergedState",
    "merge_parallel_results",
]
