"""Multi-agent contracts, registry, state merge, serialization, and planning."""

from multi_agent.contracts import (
    ActionProposal,
    ActionRiskLevel,
    AgentAuthority,
    AgentCapability,
    AgentError,
    AgentErrorCategory,
    AgentExecutionContext,
    AgentResult,
    AgentTask,
    ComplexityDecision,
    Evidence,
    EvidenceType,
    ExecutionBudget,
    ExecutionUsage,
    MultiAgentState,
    ProviderMetadata,
    StrictContract,
    TokenUsage,
    ToolAuthority,
    ToolCallRecord,
    ToolDescriptor,
    UsageAvailabilityStatus,
    from_crm_writer_proposal,
    from_productivity_proposal,
)
from multi_agent.errors import (
    BudgetExceededError,
    CapabilityValidationError,
    DisabledAgentError,
    DuplicateAgentError,
    DuplicateToolError,
    ForeignTenantEvidenceError,
    MergeConflictError,
    MultiAgentError,
    ProposalHashMismatchError,
    SerializationError,
    UnauthorizedToolError,
    UnknownAgentError,
    UnknownToolError,
)
from multi_agent.integrity import compute_proposal_hash
from multi_agent.registry import (
    AgentHandler,
    AgentRegistry,
    RegistrySnapshot,
    ToolCatalog,
)
from multi_agent.serialization import (
    canonicalize,
    content_hash,
    deserialize_contract,
    serialize_contract,
    serialize_set_for_json,
    stable_hash,
    validate_strict_json,
)
from multi_agent.state import MergeConflict, MergedState, merge_parallel_results

# Phase 3 — planning
from multi_agent.complexity_gate import (
    DETERMINISTIC_EVENT_TYPES,
    KAFKA_TOPIC_TO_EVENT_TYPE,
    REASON_CONFLICTING_SIGNALS,
    REASON_CROSS_DOMAIN_OBJECTIVE,
    REASON_CUSTOMER_RECOVERY_TEMPLATE,
    REASON_FIXED_EVENT_ALLOWLIST,
    REASON_MULTIPLE_TASK_TYPES,
    REASON_SINGLE_DOMAIN_SINGLE_TASK,
    RuleBasedComplexityGate,
)
from multi_agent.planning import (
    CODE_APPROVAL_REQUEST_MISSING_PROPOSE,
    CODE_INTENT_CYCLE,
    CODE_INTENT_DUPLICATE_ID,
    CODE_INTENT_MISSING_DEPENDENCY,
    CODE_WRITE_REQUEST_MISSING_PROPOSE,
    MAX_ASSIGNMENT_COMBINATIONS,
    NEVER_RETRYABLE_ERROR_CODES,
    PLANNER_VERSION,
    PlanDraft,
    PlanValidationIssue,
    PlanValidationReport,
    PlannedTask,
    PlanningRequest,
    PlanningSignals,
    RequestedTask,
    RetryPolicy,
    TaskIntent,
    TOOL_TO_AGENT_AUTHORITY,
    build_expected_planned_tasks,
    canonical_complexity_payload,
    canonical_request_payload,
    compute_plan_hash,
    compute_request_hash,
    effective_domains,
    effective_task_types,
    resolve_agent_assignment,
    resolve_candidate_agents,
    resolve_expected_intents,
    task_intent_from_requested_task,
    validate_intent_graph,
    validate_intent_tool_authority,
    validate_write_approval_requirements,
)
from multi_agent.planning_errors import (
    AmbiguousAgentSelectionError,
    BudgetExceededPlanningError,
    InsufficientContextError,
    PlanCycleError,
    PlanIntegrityError,
    PlanValidationError,
    PlanningError,
    PlanningInputError,
    RegistryVersionMismatchError,
    UnsupportedCapabilityError,
)
from multi_agent.planning_templates import (
    CUSTOMER_RECOVERY_DOMAIN,
    DEFAULT_CUSTOMER_RECOVERY_TEMPLATE,
    CustomerRecoveryTemplate,
    INTENT_CUSTOMER_CONTEXT,
    INTENT_KNOWLEDGE_RECOMMENDATION,
    INTENT_RECOVERY_METRICS,
    INTENT_SALES_RISK_ANALYSIS,
    INTENT_SUPPORT_ANALYSIS,
)
from multi_agent.plan_validator import PlanValidator
from multi_agent.planner import DeterministicPlanner

# Phase 4 — Supervisor Runtime
from multi_agent.execution import (
    ExecutionBinding,
    ExecutionCancellation,
    ExecutionTraceEvent,
    FakeExecutionCancellation,
    SupervisorConfig,
    SupervisorRunResult,
    SupervisorRunStatus,
    TaskAttemptRecord,
    TaskExecutionRecord,
    TRACE_BUDGET_EXCEEDED,
    TRACE_PLAN_VALIDATED,
    TRACE_RESULTS_MERGED,
    TRACE_RUN_CANCELLED,
    TRACE_RUN_COMPLETED,
    TRACE_RUN_STARTED,
    TRACE_TASK_COMPLETED,
    TRACE_TASK_FAILED,
    TRACE_TASK_NEEDS_INPUT,
    TRACE_TASK_READY,
    TRACE_TASK_RETRYING,
    TRACE_TASK_SKIPPED,
    TRACE_TASK_STARTED,
    TRACE_TASK_TIMED_OUT,
    build_execution_context,
    final_status_priority,
    utc_now,
    validate_agent_result,
)
from multi_agent.execution_errors import (
    ExecutionUsageUnavailableError,
    InvalidAgentResultError,
    InvalidInvocationReceiptError,
    NonRetryableAgentError,
    RetryableAgentError,
    RunAlreadyInProgressError,
    RunPlanConflictError,
    SupervisorError,
)
from multi_agent.invocation import (
    AgentInvocationReceipt,
    AgentInvocationFailure,
    AgentInvocationOutcome,
    AgentInvoker,
    DeterministicFakeInvoker,
    RegistryAgentInvoker,
    validate_invocation_receipt,
)

# R10 Sync 1: Usage types are now imported directly from
# :mod:`multi_agent.usage` (the canonical source) rather than through
# :mod:`multi_agent.invocation`'s compatibility re-export.  This
# ensures ``multi_agent.AttemptUsageRecord is multi_agent.usage.AttemptUsageRecord``
# — there is exactly one definition source.
from multi_agent.usage import (
    ERROR_EXECUTION_USAGE_UNAVAILABLE,
    ERROR_INFRASTRUCTURE_EXCEPTION,
    ERROR_INVALID_INVOCATION_OUTCOME,
    ERROR_TOOL_USAGE_UNAVAILABLE,
    ERROR_USAGE_SOURCE_MISMATCH,
    AttemptUsageDisposition,
    AttemptUsageRecord,
    ProviderUsageVerifier,
    UsageProvenance,
    # R7 P1-1: DEPRECATED — ``UsageTrustLevel`` is retained for
    # backwards compatibility but new code must use ``UsageProvenance``
    # and ``AttemptUsageDisposition``.  The legacy ``usage_trust`` field
    # on ``AgentInvocationReceipt`` is auto-derived from
    # ``usage_provenance`` and will be removed in the next incompatible
    # version.
    UsageTrustLevel,
    UsageVerificationCapabilities,
    VerifiedUsage,
    get_usage_capabilities,
    validate_usage_dimension,
)
from multi_agent.run_store import (
    InMemoryRunStore,
    RunIdentity,
    RunIdentityStatus,
    RunLease,
    RunStore,
    defensive_copy_result,
)
from multi_agent.scheduler import (
    AgentCallPermit,
    BeforeWave,
    DagScheduler,
    DispatchDecision,
    PreDispatch,
    TaskOutcome,
    WaveCallback,
    WaveStartedCallback,
)
from multi_agent.supervisor import SupervisorRuntime
from multi_agent.supervisor_graph import (
    FakeSupervisorRuntime,
    SupervisorGraphState,
    build_supervisor_graph,
)

# Phase 5A — Reviewer & Governance Decision Layer
from multi_agent.review_errors import (
    AuthorityViolationError,
    InvalidEvidenceReferenceError,
    InvalidProposalIdentityError,
    InvalidReviewRequestError,
    InvalidReviewResultError,
    PolicyEvaluationError,
    ReviewConflictError,
    ReviewError,
    ReviewIntegrityError,
    UnknownActionError,
)
from multi_agent.review_contracts import (
    CODE_ACTION_CATEGORY_NOT_REVIEWABLE,
    CODE_ACTION_PARAMETER_INVALID,
    CODE_ACTION_TOOL_FORBIDDEN,
    CODE_ACTION_UNKNOWN_TOOL,
    CODE_ACTION_UNKNOWN_TYPE,
    CODE_AUTHORITY_EXCEEDS_SNAPSHOT,
    CODE_AUTHORITY_INSUFFICIENT,
    CODE_AUTHORITY_PROPOSE_EXECUTE,
    CODE_AUTHORITY_READ_ONLY_WRITE,
    CODE_CONFLICT_ACTIVATE_DEACTIVATE,
    CODE_CONFLICT_CREATE_DELETE,
    CODE_CONFLICT_FIELD_VALUE,
    CODE_CONFLICT_IDEMPOTENCY_MISMATCH,
    CODE_CONFLICT_MUTEX_NOTIFICATION,
    CODE_CONFLICT_OWNER_REASSIGN,
    CODE_DUPLICATE_DEDUPED,
    CODE_DUPLICATE_DETECTED,
    CODE_EVIDENCE_DANGLING,
    CODE_EVIDENCE_DUPLICATE,
    CODE_EVIDENCE_FOREIGN_TENANT,
    CODE_EVIDENCE_HASH_MISMATCH,
    CODE_EVIDENCE_MISSING,
    CODE_EVIDENCE_TYPE_MISMATCH,
    CODE_IDEMPOTENCY_BLANK,
    CODE_IDEMPOTENCY_INCONSISTENT,
    CODE_IDEMPOTENCY_MISSING,
    CODE_IDENTITY_DUPLICATE_PROPOSAL_ID,
    CODE_IDENTITY_MISMATCH,
    CODE_POLICY_DENIED,
    CODE_POLICY_NEEDS_APPROVAL,
    CODE_POLICY_NEEDS_INPUT,
    CODE_RISK_CRITICAL_NEEDS_APPROVAL,
    CODE_RISK_HIGH_NEEDS_APPROVAL,
    CODE_RISK_REQUIRES_EVIDENCE,
    CODE_TENANT_CROSS_REFERENCE,
    CODE_TENANT_PII_EGRESS,
    CODE_TENANT_SECRET_FIELD,
    REJECTION_FINDING_CODES,
    REVIEWER_VERSION,
    CapabilitySnapshot,
    PolicyContext,
    ProposalReview,
    ReviewBatchResult,
    ReviewBatchStatus,
    ReviewDecisionStatus,
    ReviewFinding,
    ReviewFindingSeverity,
    ReviewProposalEnvelope,
    ReviewRequest,
    ReviewRiskLevel,
    TaskRecordSummary,
    TraceSummary,
    batch_status_priority,
    canonical_review_request_payload,
    proposal_status_to_batch,
)
from multi_agent.policy import (
    DeterministicPolicyEvaluator,
    FakePolicyEvaluator,
    OPAReviewAdapter,
    OPAReviewAdapterConfig,
    PolicyDecision,
    PolicyEvaluationRequest,
    PolicyEvaluationResult,
    PolicyEvaluator,
    PolicyMatchedRule,
)
from multi_agent.evidence_review import (
    build_evidence_index,
    compute_review_evidence_hash,
    detect_dangling_evidence,
    detect_duplicate_evidence,
    validate_evidence_for_proposal,
)
from multi_agent.conflict_resolution import (
    ConflictGroup,
    ConflictResult,
    DeduplicationResult,
    DuplicateGroup,
    compute_canonical_key,
    detect_conflicts,
    detect_duplicates,
    detect_idempotency_key_conflicts,
)
from multi_agent.reviewer import (
    ProposalReviewer,
    classify_risk,
    validate_action_allowlist,
    validate_authority,
    validate_idempotency,
    validate_identity,
    validate_tenant_safety,
)
from multi_agent.review_evaluation import (
    ReviewFixture,
    ReviewMetrics,
    build_review_fixtures,
    build_review_request,
    compute_review_metrics,
    default_policy_context,
)
from multi_agent.review_graph import (
    FakeProposalReviewer,
    ReviewGraphState,
    build_review_graph,
)

__all__ = [
    # Phase 2
    "ActionProposal",
    "ActionRiskLevel",
    "AgentAuthority",
    "AgentCapability",
    "AgentError",
    "AgentErrorCategory",
    "AgentExecutionContext",
    "AgentHandler",
    "AgentRegistry",
    "AgentResult",
    "AgentTask",
    "BudgetExceededError",
    "CapabilityValidationError",
    "ComplexityDecision",
    "DisabledAgentError",
    "DuplicateAgentError",
    "DuplicateToolError",
    "Evidence",
    "EvidenceType",
    "ExecutionBudget",
    "ExecutionUsage",
    "ForeignTenantEvidenceError",
    "UsageAvailabilityStatus",
    "MergeConflict",
    "MergeConflictError",
    "MergedState",
    "MultiAgentError",
    "MultiAgentState",
    "ProposalHashMismatchError",
    "ProviderMetadata",
    "RegistrySnapshot",
    "SerializationError",
    "StrictContract",
    "TokenUsage",
    "ToolAuthority",
    "ToolCallRecord",
    "ToolCatalog",
    "ToolDescriptor",
    "UnauthorizedToolError",
    "UnknownAgentError",
    "UnknownToolError",
    "canonicalize",
    "compute_proposal_hash",
    "content_hash",
    "deserialize_contract",
    "from_crm_writer_proposal",
    "from_productivity_proposal",
    "merge_parallel_results",
    "serialize_contract",
    "serialize_set_for_json",
    "stable_hash",
    "validate_strict_json",
    # Phase 3 — Complexity Gate
    "DETERMINISTIC_EVENT_TYPES",
    "KAFKA_TOPIC_TO_EVENT_TYPE",
    "REASON_CONFLICTING_SIGNALS",
    "REASON_CROSS_DOMAIN_OBJECTIVE",
    "REASON_CUSTOMER_RECOVERY_TEMPLATE",
    "REASON_FIXED_EVENT_ALLOWLIST",
    "REASON_MULTIPLE_TASK_TYPES",
    "REASON_SINGLE_DOMAIN_SINGLE_TASK",
    "RuleBasedComplexityGate",
    # Phase 3 — Planning
    "CODE_APPROVAL_REQUEST_MISSING_PROPOSE",
    "CODE_INTENT_CYCLE",
    "CODE_INTENT_DUPLICATE_ID",
    "CODE_INTENT_MISSING_DEPENDENCY",
    "CODE_WRITE_REQUEST_MISSING_PROPOSE",
    "MAX_ASSIGNMENT_COMBINATIONS",
    "NEVER_RETRYABLE_ERROR_CODES",
    "PLANNER_VERSION",
    "PlanDraft",
    "PlanValidationIssue",
    "PlanValidationReport",
    "PlannedTask",
    "PlanningRequest",
    "PlanningSignals",
    "RequestedTask",
    "RetryPolicy",
    "TaskIntent",
    "TOOL_TO_AGENT_AUTHORITY",
    "build_expected_planned_tasks",
    "canonical_complexity_payload",
    "canonical_request_payload",
    "compute_plan_hash",
    "compute_request_hash",
    "effective_domains",
    "effective_task_types",
    "resolve_agent_assignment",
    "resolve_candidate_agents",
    "resolve_expected_intents",
    "task_intent_from_requested_task",
    "validate_intent_graph",
    "validate_intent_tool_authority",
    "validate_write_approval_requirements",
    # Phase 3 — Errors
    "AmbiguousAgentSelectionError",
    "BudgetExceededPlanningError",
    "InsufficientContextError",
    "PlanCycleError",
    "PlanIntegrityError",
    "PlanValidationError",
    "PlanningError",
    "PlanningInputError",
    "RegistryVersionMismatchError",
    "UnsupportedCapabilityError",
    # Phase 3 — Templates
    "CUSTOMER_RECOVERY_DOMAIN",
    "DEFAULT_CUSTOMER_RECOVERY_TEMPLATE",
    "CustomerRecoveryTemplate",
    "INTENT_CUSTOMER_CONTEXT",
    "INTENT_KNOWLEDGE_RECOMMENDATION",
    "INTENT_RECOVERY_METRICS",
    "INTENT_SALES_RISK_ANALYSIS",
    "INTENT_SUPPORT_ANALYSIS",
    # Phase 3 — Validator & Planner
    "PlanValidator",
    "DeterministicPlanner",
    # Phase 4 — Execution Errors
    "ExecutionUsageUnavailableError",
    "InvalidAgentResultError",
    "InvalidInvocationReceiptError",
    "NonRetryableAgentError",
    "RetryableAgentError",
    "RunAlreadyInProgressError",
    "RunPlanConflictError",
    "SupervisorError",
    # Phase 4 — Invocation
    "AgentInvocationReceipt",
    "AgentInvocationFailure",
    "AgentInvocationOutcome",
    "AgentInvoker",
    "DeterministicFakeInvoker",
    "RegistryAgentInvoker",
    "validate_invocation_receipt",
    # Phase 4 — Usage (R10 Sync 1: canonical source is multi_agent.usage)
    "AttemptUsageDisposition",
    "AttemptUsageRecord",
    "ERROR_EXECUTION_USAGE_UNAVAILABLE",
    "ERROR_INFRASTRUCTURE_EXCEPTION",
    "ERROR_INVALID_INVOCATION_OUTCOME",
    "ERROR_TOOL_USAGE_UNAVAILABLE",
    "ERROR_USAGE_SOURCE_MISMATCH",
    "ProviderUsageVerifier",
    "UsageProvenance",
    # R7 P1-1: DEPRECATED — use UsageProvenance / AttemptUsageDisposition.
    "UsageTrustLevel",
    "UsageVerificationCapabilities",
    "VerifiedUsage",
    "get_usage_capabilities",
    "validate_usage_dimension",
    # Phase 4 — Execution Contracts
    "ExecutionBinding",
    "ExecutionCancellation",
    "ExecutionTraceEvent",
    "FakeExecutionCancellation",
    "SupervisorConfig",
    "SupervisorRunResult",
    "SupervisorRunStatus",
    "TaskAttemptRecord",
    "TaskExecutionRecord",
    "TRACE_BUDGET_EXCEEDED",
    "TRACE_PLAN_VALIDATED",
    "TRACE_RESULTS_MERGED",
    "TRACE_RUN_CANCELLED",
    "TRACE_RUN_COMPLETED",
    "TRACE_RUN_STARTED",
    "TRACE_TASK_COMPLETED",
    "TRACE_TASK_FAILED",
    "TRACE_TASK_NEEDS_INPUT",
    "TRACE_TASK_READY",
    "TRACE_TASK_RETRYING",
    "TRACE_TASK_SKIPPED",
    "TRACE_TASK_STARTED",
    "TRACE_TASK_TIMED_OUT",
    "build_execution_context",
    "final_status_priority",
    "utc_now",
    "validate_agent_result",
    # Phase 4 — Run Store
    "InMemoryRunStore",
    "RunIdentity",
    "RunIdentityStatus",
    "RunLease",
    "RunStore",
    "defensive_copy_result",
    # Phase 4 — Scheduler & Supervisor
    "AgentCallPermit",
    "BeforeWave",
    "DagScheduler",
    "DispatchDecision",
    "PreDispatch",
    "TaskOutcome",
    "WaveCallback",
    "WaveStartedCallback",
    "SupervisorRuntime",
    # Phase 4 — LangGraph Adapter
    "FakeSupervisorRuntime",
    "SupervisorGraphState",
    "build_supervisor_graph",
    # Phase 5A — Review Errors
    "AuthorityViolationError",
    "InvalidEvidenceReferenceError",
    "InvalidProposalIdentityError",
    "InvalidReviewRequestError",
    "InvalidReviewResultError",
    "PolicyEvaluationError",
    "ReviewConflictError",
    "ReviewError",
    "ReviewIntegrityError",
    "UnknownActionError",
    # Phase 5A — Review Contracts
    "CODE_ACTION_CATEGORY_NOT_REVIEWABLE",
    "CODE_ACTION_PARAMETER_INVALID",
    "CODE_ACTION_TOOL_FORBIDDEN",
    "CODE_ACTION_UNKNOWN_TOOL",
    "CODE_ACTION_UNKNOWN_TYPE",
    "CODE_AUTHORITY_EXCEEDS_SNAPSHOT",
    "CODE_AUTHORITY_INSUFFICIENT",
    "CODE_AUTHORITY_PROPOSE_EXECUTE",
    "CODE_AUTHORITY_READ_ONLY_WRITE",
    "CODE_CONFLICT_ACTIVATE_DEACTIVATE",
    "CODE_CONFLICT_CREATE_DELETE",
    "CODE_CONFLICT_FIELD_VALUE",
    "CODE_CONFLICT_IDEMPOTENCY_MISMATCH",
    "CODE_CONFLICT_MUTEX_NOTIFICATION",
    "CODE_CONFLICT_OWNER_REASSIGN",
    "CODE_DUPLICATE_DEDUPED",
    "CODE_DUPLICATE_DETECTED",
    "CODE_EVIDENCE_DANGLING",
    "CODE_EVIDENCE_DUPLICATE",
    "CODE_EVIDENCE_FOREIGN_TENANT",
    "CODE_EVIDENCE_HASH_MISMATCH",
    "CODE_EVIDENCE_MISSING",
    "CODE_EVIDENCE_TYPE_MISMATCH",
    "CODE_IDEMPOTENCY_BLANK",
    "CODE_IDEMPOTENCY_INCONSISTENT",
    "CODE_IDEMPOTENCY_MISSING",
    "CODE_IDENTITY_DUPLICATE_PROPOSAL_ID",
    "CODE_IDENTITY_MISMATCH",
    "CODE_POLICY_DENIED",
    "CODE_POLICY_NEEDS_APPROVAL",
    "CODE_POLICY_NEEDS_INPUT",
    "CODE_RISK_CRITICAL_NEEDS_APPROVAL",
    "CODE_RISK_HIGH_NEEDS_APPROVAL",
    "CODE_RISK_REQUIRES_EVIDENCE",
    "CODE_TENANT_CROSS_REFERENCE",
    "CODE_TENANT_PII_EGRESS",
    "CODE_TENANT_SECRET_FIELD",
    "REJECTION_FINDING_CODES",
    "REVIEWER_VERSION",
    "CapabilitySnapshot",
    "PolicyContext",
    "ProposalReview",
    "ReviewBatchResult",
    "ReviewBatchStatus",
    "ReviewDecisionStatus",
    "ReviewFinding",
    "ReviewFindingSeverity",
    "ReviewProposalEnvelope",
    "ReviewRequest",
    "ReviewRiskLevel",
    "TaskRecordSummary",
    "TraceSummary",
    "batch_status_priority",
    "canonical_review_request_payload",
    "proposal_status_to_batch",
    # Phase 5A — Policy Evaluator
    "DeterministicPolicyEvaluator",
    "FakePolicyEvaluator",
    "OPAReviewAdapter",
    "OPAReviewAdapterConfig",
    "PolicyDecision",
    "PolicyEvaluationRequest",
    "PolicyEvaluationResult",
    "PolicyEvaluator",
    "PolicyMatchedRule",
    # Phase 5A — Evidence Review
    "build_evidence_index",
    "compute_review_evidence_hash",
    "detect_dangling_evidence",
    "detect_duplicate_evidence",
    "validate_evidence_for_proposal",
    # Phase 5A — Conflict Resolution
    "ConflictGroup",
    "ConflictResult",
    "DeduplicationResult",
    "DuplicateGroup",
    "compute_canonical_key",
    "detect_conflicts",
    "detect_duplicates",
    "detect_idempotency_key_conflicts",
    # Phase 5A — Reviewer
    "ProposalReviewer",
    "classify_risk",
    "validate_action_allowlist",
    "validate_authority",
    "validate_idempotency",
    "validate_identity",
    "validate_tenant_safety",
    # Phase 5A — Evaluation (Phase 4 Adapter, Fixtures, Metrics)
    "ReviewFixture",
    "ReviewMetrics",
    "build_review_fixtures",
    "build_review_request",
    "compute_review_metrics",
    "default_policy_context",
    # Phase 5A — LangGraph Review Adapter
    "FakeProposalReviewer",
    "ReviewGraphState",
    "build_review_graph",
]
